disabled_rules:
  - file_length # Files should not span too many lines - They shouldn't, but we're not enforcing a specific limit on this.
  - function_body_length # Functions bodies should not span too many lines - They shouldn't, but we're not enforcing a specific limit on this.
  - function_parameter_count # Number of function parameters should be low - They may need to be high for dependency injection.
  - type_body_length # Type bodies should not span too many lines - They shouldn't, but we're not enforcing a specific limit on this.
  - line_length
opt_in_rules:
  - contains_over_first_not_nil # Prefer contains over first(where:) != nil
  - empty_count # Prefer checking isEmpty over comparing count to zero.
  - empty_string # Prefer checking isEmpty over comparing string to an empty string literal.
  - explicit_init # Explicitly calling .init() should be avoided.
  - fatal_error_message # A fatalError call should have a message.
  - first_where # .first(where:) over .filter { }.first in collections.
  - implicitly_unwrapped_optional # Implicitly unwrapped optionals should be avoided when possible.
  - operator_usage_whitespace # Operators should be surrounded by a single whitespace when they are being used.
  - overridden_super_call # Some overridden methods should always call super
  - override_in_extension # Extensions shouldn't override declarations.
  - private_unit_test # Unit tests should not be marked private because they are silently skipped.
  - prohibited_super_call # Some methods should not call super
  - redundant_nil_coalescing # nil coalescing operator is only evaluated if the lhs is nil, coalescing operator with nil as rhs is redundant
  - switch_case_on_newline # Cases inside a switch should always be on a newline
  - yoda_condition # The variable should be placed on the left, the constant on the right of a comparison operator.
  - modifier_order # Modifier order should be consistent.
  - explicit_self # Instance variables and functions should be explicitly accessed with ‘self.’
  - weak_delegate # Delegates should be weak to avoid reference cycles.
  - closure_spacing # Closure expressions should have a single space inside each brace.
  - collection_alignment # All elements in a collection literal should be vertically aligned
  - closure_end_indentation # Closure end should have the same indentation as the line that started it.

trailing_whitespace:
  ignores_empty_lines: true # don't try to make people delete trailing whitespace from empty lines

identifier_name:
  excluded: [id, uid, vc]

type_name:
  excluded: [id, uid]

line_length:
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

cyclomatic_complexity:
  ignores_case_statements: true

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Sudo/Library/Vendor
  - sudoTests/Library/Vendor
  - Pods
